- name: Transfer SQL Schema file
  copy:
    src: files/schema.mysql.sql
    dest: /tmp
    
- name: Import the initial PowerDNS MySQL schema
  mysql_db:
    login_user: "{{ pdns_database_user }}"
    login_password: "{{ pdns_database_password }}"
    login_host: "{{ hostvars[db_master]['ansible_all_ipv4_addresses'][0] }}"
    name: "{{ pdns_database_name }}"
    state: import
    target: /tmp/schema.mysql.sql
  ignore_errors: true
  