---

dependency:
  name: galaxy
  requirements_file: 'tests/requirements.yml'

ansible:
  playbook: 'tests/playbook.yml'
  group_vars:
    master:
      pdns_install_repo: "{{ pdns_auth_powerdns_repo_master }}"
    sqlite:
      pdns_install_repo: "{{ pdns_auth_powerdns_repo_master }}"
      pdns_backends_sqlite3_databases:
        - '/var/lib/powerdns/pdns.db'
      pdns_backends:
        gsqlite3:
          database: '/var/lib/powerdns/pdns.db'
          dnssec: yes
    mysql:
      pdns_install_repo: "{{ pdns_auth_powerdns_repo_40 }}"
      pdns_backends_mysql_credential:
        gmysql:
          priv_user: 'root'
          priv_password: ''
          priv_host:
            - '%'
            - 'localhost'
      pdns_backends:
        gmysql:
          host: 'localhost'
          dbname: pdns
          user: pdns
          password: pdns

driver:
  name: vagrant
vagrant:
  platforms:
    - name: CentOS-7
      box: centos/7
    - name: Debian-Jessie
      box: debian/jessie64
  providers:
    - name: libvirt
      type: libvirt
      driver: qemu
      options:
        cpu_mode: 'host-passthrough'
        memory: 512
        cpus: 2
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512 
        cpus: 2
  instances:
    - name: master
      ansible_groups:
        - master
    - name: sqlite
      ansible_groups:
        - sqlite
    - name: mysql
      ansible_groups:
        - mysql
